data:
    neo4j:
      uri: 'bolt://localhost'
      username: 'neo4j'
      password: 'root'
      
server:
  port: 80
  servlet:
    session:
      timeout: 60m
      cookie:
        max-age: 60m
